//
//  PriceResponseTests.swift
//  BusinessMath
//
//  Fitting a demand curve in three functional forms, and the three ways the fit reads as
//  an answer when it is not one.
//
//  - **Choosing the form by R².** Each form is fitted in the space it is linear in —
//    quantity, or log-quantity — so the R² values score different dependent variables.
//    Data generated by a straight line gives a log-log fit an R² of 0.975, which almost
//    anyone would report as a good fit, while the same curve is out by 2.75 units of
//    quantity at every point. Comparison has to happen in units of quantity.
//  - **Quoting "the elasticity" of a non-log-log curve.** On a linear demand curve
//    elasticity is `bP/Q`, running from near zero to unbounded along the same curve. A
//    single number lifted out of it is a reading at some price nobody recorded.
//  - **Extrapolating a linear curve past its choke price.** Quantity goes negative,
//    revenue follows it, and profit comes back as a loss — three well-formed numbers
//    describing a region where the model says nothing.
//
//  The anchor is the Lerner condition, `(P* − c)/P* = −1/ε(P*)`. It is the first-order
//  condition for profit restated, so it must hold at the optimum of **every** form. Three
//  closed-form optima and three different elasticity functions are checked against it
//  here, and no reference implementation is involved.
//

import Testing
import Foundation
import Numerics
@testable import BusinessMath

@Suite("Price response")
struct PriceResponseTests {

	static let prices: [Double] = [10, 12, 14, 16, 18, 20]

	/// Exactly `Q = 200 − 5P`.
	static let linearQuantities: [Double] = prices.map { 200 - 5 * $0 }

	/// Exactly `Q = 1000 · P^−1.5`.
	static let logLogQuantities: [Double] = prices.map { 1000 * Double.pow($0, -1.5) }

	/// Exactly `Q = 500 · e^−0.1P`.
	static let semiLogQuantities: [Double] = prices.map { 500 * Double.exp(-0.1 * $0) }

	static func generated(_ form: DemandForm) -> [Double] {
		switch form {
		case .linear: return linearQuantities
		case .logLog: return logLogQuantities
		case .semiLog: return semiLogQuantities
		}
	}

	// MARK: - Recovery

	@Test("Each form recovers the parameters it was generated from")
	func formsRecoverTheirOwnParameters() throws {
		let linear = try #require(PriceResponseCurve(prices: Self.prices,
													 quantities: Self.linearQuantities,
													 form: .linear))
		#expect(Swift.abs(linear.slope - (-5)) < 1e-10, "slope \(linear.slope)")
		#expect(Swift.abs(linear.intercept - 200) < 1e-9, "intercept \(linear.intercept)")

		let logLog = try #require(PriceResponseCurve(prices: Self.prices,
													 quantities: Self.logLogQuantities,
													 form: .logLog))
		#expect(Swift.abs(logLog.slope - (-1.5)) < 1e-12, "slope \(logLog.slope)")

		let semiLog = try #require(PriceResponseCurve(prices: Self.prices,
													  quantities: Self.semiLogQuantities,
													  form: .semiLog))
		#expect(Swift.abs(semiLog.slope - (-0.1)) < 1e-12, "slope \(semiLog.slope)")
	}

	@Test("The fitted line passes through the mean point")
	func fitPassesThroughTheMeanPoint() throws {
		let curve = try #require(PriceResponseCurve(prices: Self.prices,
													quantities: Self.semiLogQuantities,
													form: .linear))
		let meanPrice: Double = Self.prices.reduce(0, +) / Double(Self.prices.count)
		let total: Double = Self.semiLogQuantities.reduce(0, +)
		let meanQuantity: Double = total / Double(Self.semiLogQuantities.count)
		let fitted = try #require(curve.quantity(at: meanPrice))
		#expect(Swift.abs(fitted - meanQuantity) < 1e-9, "\(fitted) against \(meanQuantity)")
	}

	@Test("The log-log form is exactly the shipped elasticity estimator")
	func logLogMatchesPriceElasticity() throws {
		let quantities: [Double] = [100, 82, 70, 60, 53, 47]
		let curve = try #require(PriceResponseCurve(prices: Self.prices,
													quantities: quantities, form: .logLog))
		let shipped = try #require(PriceElasticity(prices: Self.prices, quantities: quantities))
		#expect(Swift.abs(curve.slope - shipped.elasticity) < 1e-12,
				"\(curve.slope) against \(shipped.elasticity)")
		#expect(Swift.abs(curve.rSquared - shipped.rSquared) < 1e-12,
				"\(curve.rSquared) against \(shipped.rSquared)")
	}

	// MARK: - The Lerner identity

	@Test("Every form's optimum satisfies the Lerner condition")
	func optimaSatisfyLerner() throws {
		let cost: Double = 10
		for form in DemandForm.allCases {
			let curve = try #require(PriceResponseCurve(prices: Self.prices,
														quantities: Self.generated(form),
														form: form))
			let star = try #require(curve.optimalPrice(marginalCost: cost))
			let epsilon = try #require(curve.elasticity(at: star))
			let margin: Double = star - cost
			let lerner: Double = margin / star
			let inverse: Double = -1 / epsilon
			let gap: Double = lerner - inverse
			#expect(Swift.abs(gap) < 1e-9, "\(form): \(lerner) against \(inverse)")
		}
	}

	@Test("The optima are the closed forms, at the prices worked out by hand")
	func optimaMatchTheClosedForms() throws {
		let cost: Double = 10
		// Linear: (bc − a)/2b = (−50 − 200)/−10 = 25.
		let linear = try #require(PriceResponseCurve(prices: Self.prices,
													 quantities: Self.linearQuantities,
													 form: .linear))
		let linearStar = try #require(linear.optimalPrice(marginalCost: cost))
		#expect(Swift.abs(linearStar - 25) < 1e-9, "linear \(linearStar)")

		// Log-log: cb/(b + 1) = 10 · −1.5 / −0.5 = 30.
		let logLog = try #require(PriceResponseCurve(prices: Self.prices,
													 quantities: Self.logLogQuantities,
													 form: .logLog))
		let logLogStar = try #require(logLog.optimalPrice(marginalCost: cost))
		#expect(Swift.abs(logLogStar - 30) < 1e-9, "log-log \(logLogStar)")

		// Semi-log: c − 1/b = 10 + 10 = 20.
		let semiLog = try #require(PriceResponseCurve(prices: Self.prices,
													  quantities: Self.semiLogQuantities,
													  form: .semiLog))
		let semiLogStar = try #require(semiLog.optimalPrice(marginalCost: cost))
		#expect(Swift.abs(semiLogStar - 20) < 1e-9, "semi-log \(semiLogStar)")
	}

	@Test("Profit really is maximised there, checked against its neighbours")
	func theOptimumIsAMaximum() throws {
		let cost: Double = 10
		for form in DemandForm.allCases {
			let curve = try #require(PriceResponseCurve(prices: Self.prices,
														quantities: Self.generated(form),
														form: form))
			let star = try #require(curve.optimalPrice(marginalCost: cost))
			let best = try #require(curve.profit(at: star, marginalCost: cost))
			let below = try #require(curve.profit(at: star - 1, marginalCost: cost))
			let above = try #require(curve.profit(at: star + 1, marginalCost: cost))
			#expect(best > below, "\(form): \(best) against \(below) one lower")
			#expect(best > above, "\(form): \(best) against \(above) one higher")
		}
	}

	// MARK: - Elasticity is a point reading

	@Test("Elasticity varies along a linear curve and is constant on a log-log one")
	func elasticityVariesExceptOnLogLog() throws {
		let linear = try #require(PriceResponseCurve(prices: Self.prices,
													 quantities: Self.linearQuantities,
													 form: .linear))
		let low = try #require(linear.elasticity(at: 10))
		let high = try #require(linear.elasticity(at: 30))
		// −5·10/150 against −5·30/50: the same curve, an order of magnitude apart.
		#expect(Swift.abs(low - (-1.0 / 3.0)) < 1e-9, "at 10: \(low)")
		#expect(Swift.abs(high - (-3.0)) < 1e-9, "at 30: \(high)")

		let logLog = try #require(PriceResponseCurve(prices: Self.prices,
													 quantities: Self.logLogQuantities,
													 form: .logLog))
		let cheap = try #require(logLog.elasticity(at: 10))
		let dear = try #require(logLog.elasticity(at: 30))
		#expect(Swift.abs(cheap - dear) < 1e-12, "\(cheap) against \(dear)")
	}

	// MARK: - Choosing a form

	@Test("The generating form wins on quantity-space error")
	func bestRecoversTheGeneratingForm() throws {
		for form in DemandForm.allCases {
			let quantities = Self.generated(form)
			let winner = try #require(PriceResponseCurve.best(prices: Self.prices,
															  quantities: quantities))
			#expect(winner.form == form, "generated \(form), picked \(winner.form)")
		}
	}

	@Test("A high R² in the wrong space does not identify the form")
	func rSquaredDoesNotChooseTheForm() throws {
		// The data is exactly a straight line, so the linear fit is perfect. The log-log
		// fit is the wrong shape and still scores 0.975 in its own space — a number
		// almost anyone would report as a good fit, which is why `best` does not look at
		// R² at all.
		let wrong = try #require(PriceResponseCurve(prices: Self.prices,
													quantities: Self.linearQuantities,
													form: .logLog))
		#expect(wrong.rSquared > 0.97, "log-log R² on linear data is \(wrong.rSquared)")

		let right = try #require(PriceResponseCurve(prices: Self.prices,
													quantities: Self.linearQuantities,
													form: .linear))
		let wrongError = try #require(wrong.residualSumOfSquares(prices: Self.prices,
																 quantities: Self.linearQuantities))
		let rightError = try #require(right.residualSumOfSquares(prices: Self.prices,
																 quantities: Self.linearQuantities))
		// Measured: 45.5, which is 2.75 units of quantity at every point on a curve
		// running from 150 down to 100.
		#expect(rightError < 1e-18, "the exact fit should have no error, got \(rightError)")
		#expect(wrongError > 40, "the wrong form should, got \(wrongError)")
	}

	// MARK: - Refusals

	@Test("A linear curve refuses to be read past its choke price")
	func chokePriceIsRefused() throws {
		let curve = try #require(PriceResponseCurve(prices: Self.prices,
													quantities: Self.linearQuantities,
													form: .linear))
		// Q = 200 − 5P is zero at 40 and negative above it.
		let atChoke = try #require(curve.quantity(at: 40))
		#expect(Swift.abs(atChoke) < 1e-9, "at the choke price \(atChoke)")
		#expect(curve.quantity(at: 41) == nil)
		#expect(curve.revenue(at: 41) == nil)
		#expect(curve.profit(at: 41, marginalCost: 10) == nil)
		#expect(curve.elasticity(at: 41) == nil)
	}

	@Test("An upward-sloping fit has no profit-maximising price")
	func upwardSlopeHasNoOptimum() throws {
		let rising: [Double] = [100, 110, 120, 130, 140, 150]
		for form in DemandForm.allCases {
			let curve = try #require(PriceResponseCurve(prices: Self.prices,
														quantities: rising, form: form))
			#expect(curve.slope > 0, "\(form) should slope up here")
			#expect(!curve.isDownwardSloping, "\(form)")
			#expect(curve.optimalPrice(marginalCost: 10) == nil, "\(form)")
		}
	}

	@Test("Inelastic constant-elasticity demand has no optimum")
	func inelasticLogLogHasNoOptimum() throws {
		let inelastic: [Double] = Self.prices.map { 1000 * Double.pow($0, -0.5) }
		let curve = try #require(PriceResponseCurve(prices: Self.prices,
													quantities: inelastic, form: .logLog))
		#expect(Swift.abs(curve.slope - (-0.5)) < 1e-12, "slope \(curve.slope)")
		#expect(curve.optimalPrice(marginalCost: 10) == nil)
	}

	@Test("Data the form cannot take the logarithm of is refused")
	func logarithmsAreGuarded() throws {
		// Exactly Q = 200 − 10P, which reaches its choke price inside the sample. A zero
		// quantity is a real observation, and the only thing wrong with it is that two
		// of the three forms have to take its logarithm.
		let toChoke: [Double] = Self.prices.map { 200 - 10 * $0 }
		#expect(PriceResponseCurve(prices: Self.prices, quantities: toChoke, form: .logLog) == nil)
		#expect(PriceResponseCurve(prices: Self.prices, quantities: toChoke, form: .semiLog) == nil)

		// The linear form has no logarithm to take, and recovers the line exactly.
		let linear = try #require(PriceResponseCurve(prices: Self.prices, quantities: toChoke,
													 form: .linear))
		#expect(Swift.abs(linear.slope - (-10)) < 1e-10, "slope \(linear.slope)")
		#expect(Swift.abs(linear.intercept - 200) < 1e-9, "intercept \(linear.intercept)")
		let atChoke = try #require(linear.quantity(at: 20))
		#expect(Swift.abs(atChoke) < 1e-9, "quantity at the choke price is \(atChoke)")

		let withZeroPrice: [Double] = [0, 12, 14, 16, 18, 20]
		#expect(PriceResponseCurve(prices: withZeroPrice, quantities: Self.linearQuantities,
								   form: .logLog) == nil)
	}

	@Test("Prices that never vary, and samples too small to fit, are refused")
	func degenerateSamplesAreRefused() {
		let flat: [Double] = [10, 10, 10, 10, 10, 10]
		#expect(PriceResponseCurve(prices: flat, quantities: Self.linearQuantities,
								   form: .linear) == nil)
		let two: [Double] = [10, 12]
		let pair: [Double] = [150, 140]
		#expect(PriceResponseCurve(prices: two, quantities: pair, form: .linear) == nil)
		#expect(PriceResponseCurve(prices: Self.prices, quantities: [150, 140],
								   form: .linear) == nil)
	}
}
