//
//  ProfitMargin.swift
//  BusinessMath
//
//  Created by Justin Purnell on 10/21/2025.
//

import Foundation
import Numerics

/// Calculate the profit margin.
///
/// Profit margin indicates how much profit a company earns for every dollar of
/// revenue.
///
/// - Parameters:
///   - netIncome: The net income earned by the company.
///   - revenue: The total revenue generated by the company.
///
/// - Returns: The profit margin, defined as net income divided by revenue.
///
/// - Complexity: O(1).
public func profitMargin<T: Real>(netIncome: T, revenue: T) -> T {
	guard revenue > T(0) else {
		return T(0) // Return 0 if revenue is zero or negative
	}
	return netIncome / revenue
}
