//
//  ProfitMargin.swift
//  BusinessMath
//
//  Created by Justin Purnell on 10/21/2025.
//

import Foundation
import Numerics

/// Calculate the profit margin.
///
/// Profit margin indicates how much profit a company earns for every dollar of
/// revenue.
///
/// - Parameters:
///   - netIncome: The net income earned by the company.
///   - revenue: The total revenue generated by the company.
///
/// - Returns: The profit margin, defined as net income divided by revenue.
///
/// - Complexity: O(1).
/// - Throws: `BusinessMathError.divisionByZero` if revenue is zero or negative.
public func profitMargin<T: Real>(netIncome: T, revenue: T) throws -> T {
	guard revenue > T(0) else {
		throw BusinessMathError.divisionByZero(
			context: "Profit margin: revenue must be positive"
		)
	}
	return netIncome / revenue
}
