//
//  ROE.swift
//  BusinessMath
//
//  Created by Justin Purnell on 10/21/2025.
//

import Foundation
import Numerics

/// Calculate the Return on Equity (ROE).
///
/// ROE measures a corporation's profitability and the efficiency with which it
/// generates profits from shareholders' equity.
///
/// - Parameters:
///   - netIncome: The net income generated by the company.
///   - shareholderEquity: The total equity capital invested by shareholders.
///
/// - Returns: The ROE, defined as net income divided by shareholder equity.
///
/// - Complexity: O(1).
public func roe<T: Real>(netIncome: T, shareholderEquity: T) -> T {
	guard shareholderEquity > T(0) else {
		return T(0) // Return 0 if shareholder equity is zero or negative
	}
	return netIncome / shareholderEquity
}
