//
//  CommandLineVisualization.swift
//  BusinessMath
//
//  Created by Justin Purnell on 10/22/25.
//

import Foundation

/// Visualization utilities for command-line display of simulation results and data analysis.
///
/// This module provides text-based visualization functions that render charts and graphs
/// directly in the terminal using Unicode characters and formatting.
///
/// ## Use Cases
///
/// - Display Monte Carlo simulation distributions
/// - Visualize histogram data in terminal environments
/// - Quick data exploration without external plotting tools
/// - CLI applications and scripts
///
/// ## Example
///
/// ```swift
/// let simulationData = (0..<10_000).map { _ in distributionNormal(mean: 1_000.0, stdDev: 50.0) }
/// let results = SimulationResults(values: simulationData)
/// let histogram = results.histogram(bins: 20)
/// let plot = plotHistogram(histogram)
/// print(plot)
/// ```

// MARK: - Histogram Plotting

/// Renders a horizontal bar chart histogram for command-line display.
///
/// Creates a visual representation of histogram data using Unicode block characters (█).
/// The output includes:
/// - Header with bin count and total sample count
/// - Each bin showing: range, bar graph, count, and percentage
/// - Automatic scaling so the largest bin uses the full bar width
///
/// ## Output Format
///
/// ```
/// Histogram (10 bins, 1,000 samples):
///
/// [    0.00 -   10.00):  ████████████ 234 ( 23.4%)
/// [   10.00 -   20.00):  ██████████████████ 456 ( 45.6%)
/// [   20.00 -   30.00):  ████████ 156 ( 15.6%)
/// ...
/// ```
///
/// ## Features
///
/// - **Auto-scaling**: Bars automatically scale relative to the maximum count
/// - **Unicode rendering**: Uses █ (U+2588) for solid bar appearance
/// - **Smart formatting**: Adjusts decimal places based on value magnitude
/// - **Percentage display**: Shows percentage of total for each bin
/// - **Clean alignment**: Right-aligned numbers for easy reading
///
/// ## Parameters
///
/// - Parameter histogram: Array of tuples containing range and count for each bin,
///   typically generated by `SimulationResults.histogram(bins:)`
///
/// - Returns: A formatted string containing the complete histogram visualization
///
/// ## Example
///
/// ```swift
/// // Generate histogram from simulation results
/// let revenueData = (0..<10_000).map { _ in distributionNormal(mean: 1_000.0, stdDev: 50.0) }
/// let results = SimulationResults(values: revenueData)
/// let histogram = results.histogram(bins: 20)
///
/// // Plot and display
/// let plot = plotHistogram(histogram)
/// print(plot)
///
/// // Output:
/// // Histogram (20 bins, 10,000 samples):
/// //
/// // [  950.00 - 1,000.00):  ████████████ 234 (  2.3%)
/// // [1,000.00 - 1,050.00):  ██████████████████ 456 (  4.6%)
/// // ...
/// ```
///
/// ## Customization
///
/// The function uses these default parameters:
/// - Maximum bar width: 50 characters
/// - Decimal places: 2 (auto-adjusts for large numbers)
/// - Bar character: █ (solid block)
///
/// For custom visualizations, create your own histogram data structure
/// and pass it to this function.
///
/// - Complexity: O(n) where n is the number of bins
public func plotHistogram(_ histogram: [(range: Range<Double>, count: Int)]) -> String {
	// Handle empty histogram
	guard !histogram.isEmpty else {
		return "Empty histogram"
	}

	// Calculate total count and max count for scaling
	let totalCount = histogram.reduce(0) { $0 + $1.count }
	let maxCount = histogram.map { $0.count }.max() ?? 1

	// Configuration
	let maxBarWidth = 50

	// Determine decimal places based on value magnitude
	let maxValue = histogram.map { $0.range.upperBound }.max() ?? 1.0
	let decimalPlaces: Int
	if maxValue > 1000 {
		decimalPlaces = 0
	} else if maxValue > 10 {
		decimalPlaces = 1
	} else {
		decimalPlaces = 2
	}

	// Build output string
	var output = "Histogram (\(histogram.count) bin\(histogram.count == 1 ? "" : "s"), \(totalCount) sample\(totalCount == 1 ? "" : "s")):\n\n"

	// Render each bin
	for bin in histogram {
		// Calculate bar width (proportional to count)
		let barWidth = maxCount > 0 ? Int(Double(bin.count) / Double(maxCount) * Double(maxBarWidth)) : 0
		let bar = String(repeating: "█", count: barWidth)

		// Pad bar to fixed width for alignment
		let paddedBar = bar.padding(toLength: maxBarWidth, withPad: " ", startingAt: 0)

		// Calculate percentage
		let percentage = totalCount > 0 ? (Double(bin.count) / Double(totalCount)) : 0.0

		// Format the line based on decimal places (no grouping for alignment)
		let line: String
		line = "[\(bin.range.lowerBound.number(decimalPlaces, .toNearestOrAwayFromZero, .autoupdatingCurrent, .automatic, .never).paddingLeft(toLength: 8)) - \(bin.range.upperBound.number(decimalPlaces, .toNearestOrAwayFromZero, .autoupdatingCurrent, .automatic, .never).paddingLeft(toLength: 8))):  \(paddedBar) \("\(bin.count)".paddingLeft(toLength: 4)) (\(percentage.percent(1)))\n"
		output += line
	}

	return output
}

// MARK: - Tornado Diagram Plotting

/// Renders a tornado diagram for command-line display showing sensitivity analysis results.
///
/// Creates a horizontal bar chart showing the impact of each input driver on an output metric.
/// Drivers are displayed in order of impact (largest first), with bars extending left and right
/// from a central baseline representing the base case output.
///
/// ## Output Format
///
/// ```
/// Tornado Diagram - Sensitivity Analysis
/// Base Case: 1,000.00
///
/// Revenue        ◄████████████████████████████►             Impact: 500.00 (50.0%)
///                750                     1000                     1250
///
/// Costs          ◄████████████████►                         Impact: 300.00 (30.0%)
///                850            1000                1150
///
/// Marketing      ◄████►                                     Impact: 100.00 (10.0%)
///                950   1000              1050
/// ```
///
/// ## Features
///
/// - **Ranked by impact**: Drivers with the largest impact appear first
/// - **Bidirectional bars**: Shows both decrease and increase scenarios
/// - **Base case marker**: Central vertical line shows baseline
/// - **Impact metrics**: Shows absolute and percentage impact
/// - **Value labels**: Shows low/base/high values for each driver
///
/// ## Interpretation
///
/// - **Bar length**: Longer bars = greater impact on output
/// - **Left side**: Output when driver is decreased
/// - **Right side**: Output when driver is increased
/// - **Asymmetry**: Unequal left/right bars indicate non-linear relationships
///
/// ## Parameters
///
/// - Parameter analysis: The tornado diagram analysis results from `runTornadoAnalysis(...)`
///
/// - Returns: A formatted string containing the complete tornado diagram visualization
///
/// ## Example
///
/// ```swift
/// let builder: ScenarioRunner.StatementBuilder = { _, _ in (try IncomeStatement<Double>.documentationFixture, try BalanceSheet<Double>.documentationFixture, try CashFlowStatement<Double>.documentationFixture) }
/// let baseCase = FinancialScenario.documentationFixture
/// let projection = try FinancialProjection.documentationFixture
/// let periods = Period.documentationQuarters
/// let q1 = Period.documentationQuarters[0]
/// let entity = Entity.documentationFixture
/// let incomeStatement = try IncomeStatement<Double>.documentationFixture
/// let tornado = try runTornadoAnalysis(
///     baseCase: baseCase,
///     entity: entity,
///     periods: periods,
///     inputDrivers: ["Revenue", "Costs", "Marketing"],
///     variationPercent: 0.20,
///     steps: 2,
///     builder: builder
/// ) { projection in
///     projection.incomeStatement.netIncome[q1]!
/// }
///
/// let plot = plotTornadoDiagram(tornado)
/// print(plot)
/// ```
///
/// The two half-spans of one input's bar: how far the base case sits from each end.
///
/// `lowValues` and `highValues` are keyed by whether the *input driver* was low or high, not
/// by which output is smaller — a cost driver has `low > high` — so the ends are sorted here
/// rather than assumed. A base case outside the range gives that side its full extent and the
/// other side zero, which is the honest picture: the range does not reach the base case.
///
/// - Returns: `(left, right)`, both `>= 0`, and both `0` if any input is not finite.
internal func tornadoHalfSpans(low: Double, high: Double, base: Double) -> (left: Double, right: Double) {
	let lo = Swift.min(low, high)
	let hi = Swift.max(low, high)
	let left = base - lo
	let right = hi - base
	// `>` is false for NaN, so a non-finite end collapses to a zero-width bar instead of
	// reaching `Int(_:)` with something that traps.
	let safeLeft = left > 0 ? left : 0.0
	let safeRight = right > 0 ? right : 0.0
	return (safeLeft, safeRight)
}

/// Columns for one side of a bar, by construction within `0...limit`.
///
/// This is the only place a bar width crosses from `Double` to `Int`, and it is written so
/// that neither of the two traps downstream can be reached: `Int(_:)` traps on NaN and on
/// anything outside `Int`'s range, and `String(repeating:count:)` traps on a negative count.
/// The `guard` makes the divisor visibly positive, the `min` makes the fraction visibly at
/// most one, and the clamp makes the result visibly in range — none of it is defensive
/// duplication, each step is what removes one of those traps.
///
/// - Parameters:
///   - span: The distance this side of the bar represents. Zero or negative renders nothing.
///   - scale: The span that earns the full `limit`. Zero or negative renders nothing.
///   - limit: The column budget for this side.
/// - Returns: A count in `0...limit`.
internal func tornadoBarWidth(span: Double, scale: Double, limit: Int) -> Int {
	guard scale > 0, span > 0, limit > 0 else { return 0 }
	let fraction = Swift.min(span / scale, 1.0)
	guard fraction.isFinite else { return 0 }
	let columns = Int(fraction * Double(limit))
	return Swift.max(0, Swift.min(limit, columns))
}

/// - Complexity: O(n) where n is the number of input drivers
public func plotTornadoDiagram(_ analysis: TornadoDiagramAnalysis) -> String {
	// Handle empty analysis
	guard !analysis.inputs.isEmpty else {
		return "Empty tornado diagram (no inputs)"
	}

	let baseCaseOutput = analysis.baseCaseOutput

	// Find the maximum impact, for the number formatting below.
	var maxImpact = 0.0
	for input in analysis.inputs {
		let impact = analysis.impacts[input] ?? 0.0
		maxImpact = max(maxImpact, impact)
	}

	// Bars are scaled against the widest *half*-span across all inputs, not against the widest
	// impact. Each side of a bar is padded into `maxBarWidth` columns, so a scale that lets one
	// side ask for more than that has no way to render the answer: the old code scaled the whole
	// bar to `maxBarWidth * 2` and then split it by the base case's position, which fits only
	// when the base case is exactly the midpoint. Every fixture in the suite was exactly that,
	// and anything else trapped in `String(repeating:count:)` with a negative count.
	//
	// For a symmetric input the two scales agree exactly — its half-span is `impact / 2` and the
	// scale is `maxImpact / 2` — so this changes no output that previously rendered.
	var maxHalfSpan = 0.0
	for input in analysis.inputs {
		let spans = tornadoHalfSpans(
			low: analysis.lowValues[input] ?? baseCaseOutput,
			high: analysis.highValues[input] ?? baseCaseOutput,
			base: baseCaseOutput
		)
		maxHalfSpan = max(maxHalfSpan, max(spans.left, spans.right))
	}

	// Configuration
	let maxBarWidth = 25  // Max characters for each side (left/right)
	let maxInputNameWidth = analysis.inputs.map { $0.count }.max() ?? 15

	// Determine decimal places based on magnitude
	let maxValue = max(abs(baseCaseOutput), maxImpact)
	let decimalPlaces: Int
	if maxValue > 1000 {
		decimalPlaces = 0
	} else if maxValue > 10 {
		decimalPlaces = 1
	} else {
		decimalPlaces = 2
	}

	// Build output string
	var output = "Tornado Diagram - Sensitivity Analysis\n"
	output += "Base Case: \(baseCaseOutput.number(decimalPlaces, .toNearestOrAwayFromZero, .autoupdatingCurrent, .automatic, .never))\n\n"
	
	// Format the bar line
	func barLine(_ paddedName: String, _ paddedLeftBar: String, _ paddedRightBar: String) -> String {
		return "\(paddedName) ◄\(paddedLeftBar)|\(paddedRightBar)►"
	}

	// Render each input (already sorted by impact)
	for input in analysis.inputs {
		let low = analysis.lowValues[input] ?? baseCaseOutput
		let high = analysis.highValues[input] ?? baseCaseOutput
		let impact = analysis.impacts[input] ?? 0.0

		// Each side is scaled independently against the widest half-span, so each is within
		// its own `maxBarWidth` budget without the two having to be split out of one number.
		let spans = tornadoHalfSpans(low: low, high: high, base: baseCaseOutput)
		let leftWidth = tornadoBarWidth(span: spans.left, scale: maxHalfSpan, limit: maxBarWidth)
		let rightWidth = tornadoBarWidth(span: spans.right, scale: maxHalfSpan, limit: maxBarWidth)

		// Create bars with direction indicators
		let leftBar = String(repeating: "█", count: leftWidth)
		let rightBar = String(repeating: "█", count: rightWidth)

		// Pad input name for alignment
		let paddedName = input.padding(toLength: maxInputNameWidth, withPad: " ", startingAt: 0)

		// Calculate percentage impact
		let percentImpact = baseCaseOutput != 0 ? (abs(impact) / abs(baseCaseOutput)) : 0.0 // fp-safety:disable — guarded inline

		// Pad bars: left bar is right-aligned (padding on left), right bar is left-aligned (padding on right)
		let paddedLeftBar = String(repeating: " ", count: maxBarWidth - leftWidth) + leftBar
		let paddedRightBar = rightBar.padding(toLength: maxBarWidth, withPad: " ", startingAt: 0)

		// Format impact info (no grouping for alignment)
		let impactInfo = " Impact: \(impact.number(decimalPlaces, .toNearestOrAwayFromZero, .autoupdatingCurrent, .automatic, .never)) \(percentImpact.percent(decimalPlaces == 0 ? 1 : decimalPlaces))"

		output += barLine(paddedName, paddedLeftBar, paddedRightBar) + impactInfo + "\n"

		// Add value labels underneath (no grouping for alignment)
		let valueLabels = "\(String(repeating: " ", count: maxInputNameWidth + 3))\(low.number(decimalPlaces, .toNearestOrAwayFromZero, .autoupdatingCurrent, .automatic, .never))\(String(repeating: " ", count: maxBarWidth - 8))\(baseCaseOutput.number(decimalPlaces, .toNearestOrAwayFromZero, .autoupdatingCurrent, .automatic, .never))\(String(repeating: " ", count: maxBarWidth - 8))\(high.number(decimalPlaces, .toNearestOrAwayFromZero, .autoupdatingCurrent, .automatic, .never)))"

		output += valueLabels + "\n"
	}

	return output
}

