//
//  ReferenceFixture.swift
//  BusinessMathTests
//
//  Reads the JSON generated by Scripts/reference-fixtures/generate.py.
//

import Foundation
import Testing

/// One fixture file: a set of reference cases and the authority they came from.
///
/// Cases are decoded as `[String: Double]` rather than a per-function struct so a
/// new fixture needs no new Swift type — the parameter names in the JSON are the
/// keys, and a test asks for the ones it needs by name. A misspelled key fails the
/// lookup loudly instead of silently reading a default.
struct ReferenceFixture: Sendable {

	/// The function these cases describe.
	let name: String

	/// The reference implementation and call that produced the values, verbatim.
	let reference: String

	/// Free-text note from `spec.py` — typically the parameterisation conversion.
	let note: String

	/// One dictionary per case: every parameter, plus `value` for the expected result.
	let cases: [[String: Double]]

	private struct Payload: Decodable {
		let name: String
		let reference: String
		let note: String
		let cases: [[String: Double]]
	}

	/// Loads a fixture by file basename, without the `.json`.
	///
	/// - Throws: If the resource is absent or unreadable. A missing fixture is a
	///   hard failure rather than a skip: silently passing a suite because its
	///   reference data did not load is the failure mode this whole harness exists
	///   to prevent.
	static func load(_ name: String) throws -> ReferenceFixture {
		guard let url = Bundle.module.url(forResource: name,
										  withExtension: "json",
										  subdirectory: "Fixtures")
			?? Bundle.module.url(forResource: name, withExtension: "json") else {
			throw FixtureError.missing(name)
		}
		let payload = try JSONDecoder().decode(Payload.self, from: Data(contentsOf: url))
		return ReferenceFixture(name: payload.name,
								reference: payload.reference,
								note: payload.note,
								cases: payload.cases)
	}

	enum FixtureError: Error, CustomStringConvertible {
		case missing(String)
		case missingKey(fixture: String, key: String)

		var description: String {
			switch self {
			case .missing(let name):
				return "Reference fixture '\(name).json' not found in the test bundle. "
					+ "Regenerate with Scripts/reference-fixtures/generate.py."
			case .missingKey(let fixture, let key):
				return "Fixture '\(fixture)' has a case with no '\(key)' key."
			}
		}
	}
}

extension Dictionary where Key == String, Value == Double {
	/// Reads a named parameter, throwing rather than defaulting when it is absent.
	func required(_ key: String, in fixture: String) throws -> Double {
		guard let value = self[key] else {
			throw ReferenceFixture.FixtureError.missingKey(fixture: fixture, key: key)
		}
		return value
	}
}

/// The manifest recording which SciPy produced the fixtures beside it.
struct FixtureManifest: Decodable, Sendable {
	let generated: String
	let python: String
	let scipy: String
	let numpy: String

	static func load() throws -> FixtureManifest {
		guard let url = Bundle.module.url(forResource: "MANIFEST",
										  withExtension: "json",
										  subdirectory: "Fixtures")
			?? Bundle.module.url(forResource: "MANIFEST", withExtension: "json") else {
			throw ReferenceFixture.FixtureError.missing("MANIFEST")
		}
		return try JSONDecoder().decode(FixtureManifest.self, from: Data(contentsOf: url))
	}
}
