//
//  SpecialFunctionsTests.swift
//  BusinessMathTests
//
//  The shared special-function layer under Gamma, Erlang, Chi-squared, Beta, F,
//  Pearson V, Pearson VI and the Johnson family.
//
//  Reference: scipy 1.17.1 via Scripts/reference-fixtures/generate.py. The exact
//  version is asserted below, because a parameterisation or naming change between
//  SciPy releases invalidates a fixture silently.
//

import Foundation
import Testing
import Numerics
@testable import BusinessMath

@Suite("Special Functions — SciPy reference validation")
struct SpecialFunctionsTests {

	/// The tolerance for a forward evaluation with a series or continued-fraction
	/// representation. §15.1 of the design proposal permits a documented relaxation
	/// for *root-found* quantities; a forward evaluation gets no such licence.
	static let forwardTolerance = 1e-12

	/// Root-found inverses are held to a relative tolerance rather than absolute,
	/// because the values span 1e-8 to 1e3 across the fixture and an absolute bound
	/// would be vacuous at one end and impossible at the other.
	static let inverseRelativeTolerance = 1e-9

	// MARK: - Provenance

	@Test("Fixtures were generated by the SciPy version the tests were written against")
	func manifestRecordsExpectedVersions() throws {
		let manifest = try FixtureManifest.load()
		#expect(manifest.scipy == "1.17.1",
			"""
			Fixtures were generated by scipy \(manifest.scipy), but these assertions were \
			written against 1.17.1. Re-read the fixtures before trusting a pass — SciPy has \
			renamed and reparameterised distributions between releases.
			""")
	}

	// MARK: - Regularized lower incomplete gamma, P(a, x)

	@Test("P(a, x) matches scipy.special.gammainc across both series and continued-fraction branches")
	func regularizedLowerIncompleteGammaMatchesReference() throws {
		let fixture = try ReferenceFixture.load("regularizedLowerIncompleteGamma")
		#expect(!fixture.cases.isEmpty)

		for testCase in fixture.cases {
			let a = try testCase.required("a", in: fixture.name)
			let x = try testCase.required("x", in: fixture.name)
			let expected = try testCase.required("value", in: fixture.name)

			let actual: Double = regularizedLowerIncompleteGamma(a: a, x: x)

			#expect(abs(actual - expected) < Self.forwardTolerance,
				"P(a: \(a), x: \(x)) = \(actual), expected \(expected)")
		}
	}

	@Test("P(a, x) is a probability: bounded, and non-decreasing in x")
	func regularizedLowerIncompleteGammaIsMonotoneProbability() {
		for a in [0.5, 1.0, 2.5, 10.0] {
			var previous = -1.0
			for step in 0...200 {
				let x = Double(step) * 0.25
				let p: Double = regularizedLowerIncompleteGamma(a: a, x: x)
				#expect(p >= 0.0 && p <= 1.0, "P(a: \(a), x: \(x)) = \(p) is not a probability")
				#expect(p >= previous - 1e-15, "P is decreasing at a: \(a), x: \(x)")
				previous = p
			}
		}
	}

	// MARK: - Its inverse

	@Test("Inverse of P(a, x) matches scipy.special.gammaincinv, tails included")
	func inverseRegularizedLowerIncompleteGammaMatchesReference() throws {
		let fixture = try ReferenceFixture.load("inverseRegularizedLowerIncompleteGamma")
		#expect(!fixture.cases.isEmpty)

		for testCase in fixture.cases {
			let a = try testCase.required("a", in: fixture.name)
			let p = try testCase.required("p", in: fixture.name)
			let expected = try testCase.required("value", in: fixture.name)

			let actual: Double = try inverseRegularizedLowerIncompleteGamma(p: p, a: a)

			let scale = Swift.max(abs(expected), 1e-10)
			#expect(abs(actual - expected) / scale < Self.inverseRelativeTolerance,
				"P⁻¹(a: \(a), p: \(p)) = \(actual), expected \(expected)")
		}
	}

	@Test("P and its inverse round-trip")
	func gammaInverseRoundTrips() throws {
		for a in [0.5, 1.0, 2.5, 10.0, 50.0] {
			for p in [1e-8, 0.001, 0.1, 0.5, 0.9, 0.999, 1 - 1e-8] {
				let x: Double = try inverseRegularizedLowerIncompleteGamma(p: p, a: a)
				let back: Double = regularizedLowerIncompleteGamma(a: a, x: x)
				#expect(abs(back - p) < 1e-10,
					"round trip at a: \(a), p: \(p) returned \(back)")
			}
		}
	}

	@Test("Inverse rejects probabilities outside (0, 1)")
	func gammaInverseRejectsOutOfRange() {
		for p in [-0.1, 0.0, 1.0, 1.5, Double.nan] {
			#expect(throws: (any Error).self) {
				let _: Double = try inverseRegularizedLowerIncompleteGamma(p: p, a: 2.0)
			}
		}
		for a in [-1.0, 0.0] {
			#expect(throws: (any Error).self) {
				let _: Double = try inverseRegularizedLowerIncompleteGamma(p: 0.5, a: a)
			}
		}
	}

	// MARK: - Regularized incomplete beta, I_x(a, b)

	@Test("I_x(a, b) matches scipy.special.betainc")
	func regularizedIncompleteBetaMatchesReference() throws {
		let fixture = try ReferenceFixture.load("regularizedIncompleteBeta")
		#expect(!fixture.cases.isEmpty)

		for testCase in fixture.cases {
			let a = try testCase.required("a", in: fixture.name)
			let b = try testCase.required("b", in: fixture.name)
			let x = try testCase.required("x", in: fixture.name)
			let expected = try testCase.required("value", in: fixture.name)

			let actual: Double = try regularizedIncompleteBeta(x: x, a: a, b: b)

			#expect(abs(actual - expected) < Self.forwardTolerance,
				"I_\(x)(\(a), \(b)) = \(actual), expected \(expected)")
		}
	}

	// MARK: - Its inverse

	@Test("Inverse of I_x(a, b) matches scipy.special.betaincinv, tails included")
	func inverseRegularizedIncompleteBetaMatchesReference() throws {
		let fixture = try ReferenceFixture.load("inverseRegularizedIncompleteBeta")
		#expect(!fixture.cases.isEmpty)

		for testCase in fixture.cases {
			let a = try testCase.required("a", in: fixture.name)
			let b = try testCase.required("b", in: fixture.name)
			let p = try testCase.required("p", in: fixture.name)
			let expected = try testCase.required("value", in: fixture.name)

			let actual: Double = try inverseRegularizedIncompleteBeta(p: p, a: a, b: b)

			let scale = Swift.max(abs(expected), 1e-10)
			#expect(abs(actual - expected) / scale < Self.inverseRelativeTolerance,
				"I⁻¹(p: \(p), a: \(a), b: \(b)) = \(actual), expected \(expected)")
		}
	}

	@Test("I_x and its inverse round-trip, to the accuracy the conditioning allows")
	func betaInverseRoundTrips() throws {
		for (a, b) in [(0.5, 0.5), (2.0, 3.0), (10.0, 10.0), (50.0, 2.0)] {
			for p in [1e-8, 0.001, 0.1, 0.5, 0.9, 0.999, 1 - 1e-8] {
				let x: Double = try inverseRegularizedIncompleteBeta(p: p, a: a, b: b)
				#expect(x >= 0.0 && x <= 1.0, "I⁻¹ returned \(x), outside [0, 1]")

				let back: Double = try regularizedIncompleteBeta(x: x, a: a, b: b)

				// The bound is the conditioning of the problem, not a fudge factor.
				// Moving x by a single ulp moves I_x by density(x)·ulp(x), so no
				// implementation returning a Double can round-trip tighter than that.
				//
				// The arcsine case (a = b = ½) at p = 1 − 1e-8 makes the point: the
				// root is 2.47e-16 below 1, which is between one and two ulps, so
				// (1 − x) survives with roughly one significant digit and one ulp is
				// worth 2.4e-9 in p. SciPy's own round-trip error at that point is
				// 5.1e-10. A flat 1e-10 would be asserting something no Double holds.
				let tolerance = Swift.max(1e-10, 8 * betaDensity(x, a, b) * x.ulp)
				#expect(abs(back - p) < tolerance,
					"round trip at a: \(a), b: \(b), p: \(p) returned \(back), off by \(abs(back - p)) against a conditioning bound of \(tolerance)")
			}
		}
	}

	/// The Beta(a, b) density, used to express how far one ulp of `x` moves `I_x`.
	private func betaDensity(_ x: Double, _ a: Double, _ b: Double) -> Double {
		guard x > 0, x < 1 else { return .infinity }
		let logBeta = Double.logGamma(a) + Double.logGamma(b) - Double.logGamma(a + b)
		let logDensity = (a - 1) * Double.log(x) + (b - 1) * Double.log(1 - x) - logBeta
		return Double.exp(logDensity)
	}

	@Test("Beta inverse rejects probabilities outside (0, 1) and non-positive shapes")
	func betaInverseRejectsOutOfRange() {
		for p in [-0.1, 0.0, 1.0, 1.5, Double.nan] {
			#expect(throws: (any Error).self) {
				let _: Double = try inverseRegularizedIncompleteBeta(p: p, a: 2.0, b: 3.0)
			}
		}
		#expect(throws: (any Error).self) {
			let _: Double = try inverseRegularizedIncompleteBeta(p: 0.5, a: 0.0, b: 3.0)
		}
		#expect(throws: (any Error).self) {
			let _: Double = try inverseRegularizedIncompleteBeta(p: 0.5, a: 2.0, b: -1.0)
		}
	}

	// MARK: - The existing caller must not move

	@Test("chiSquaredCDF is unchanged by the promotion")
	func chiSquaredCDFStillAgreesWithItsOwnGammaP() throws {
		// chiSquaredCDF(x, k) is P(k/2, x/2) by definition. Asserting the identity
		// rather than a table pins the refactor: if promoting the function changed
		// its behaviour, these two disagree.
		for df in [1, 2, 3, 5, 10, 30] {
			for x in [0.1, 1.0, 2.5, 5.0, 10.0, 25.0, 60.0] {
				let viaCDF: Double = try chiSquaredCDF(x: x, df: df)
				let viaGamma: Double = regularizedLowerIncompleteGamma(a: Double(df) / 2.0,
																	   x: x / 2.0)
				#expect(abs(viaCDF - viaGamma) < 1e-15,
					"chiSquaredCDF(x: \(x), df: \(df)) = \(viaCDF) but P = \(viaGamma)")
			}
		}
	}
}
